name = "sites"
compatibility_date = "2025-12-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23linVxXDCcfE3fz3y"
GITHUB_OWNER = "chrisyue888"
GITHUB_REPO = "navsphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.wnv.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://dh.wnv.dpdns.org/"

